[profile.default]
src = 'contracts'
out = 'artifactsFoundry'
libs = ['node_modules', 'lib']
test = 'testFoundry'
cache_path = 'cache_forge'

remappings = [
    'forge-std/=lib/forge-std/src/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
