type Account @entity {
  id: Bytes!
  owner: Bytes!
  createdAt: BigInt!
}

type Transaction @entity {
  id: ID!
  type: String!
  address: Bytes!
  wallet: Bytes!
  amount: BigInt!
  date: BigInt!
  status: String!
  blockNumber: BigInt!
  transactionHash: Bytes!
}

type Identity @entity {
  id: Bytes!
  ipfsCid: String!
  updatedAt: BigInt!
}

type VaultFile @entity {
  id: ID!
  user: Bytes!
  ipfsCid: String!
  addedAt: BigInt!
}

type Guardian @entity {
  id: ID!
  user: Bytes!
  guardianAddress: Bytes!
  addedAt: BigInt!
}
